object Versions {
    const val appcompat = "1.7.0"
    const val composeBom = "2025.02.00"
    const val material = "1.12.0"
    const val navigation = "2.8.7"
    const val coreKtx = "1.15.0"
    const val lifecycleRuntimeKtx = "2.8.7"
    const val activityCompose = "1.10.0"
    const val mockk = "1.13.16"
    const val junit = "4.13.2"
    const val extJunit = "1.2.1"
    const val espresso = "3.6.1"
    const val truthAssert = "1.4.4"
    const val coroutinesTest = "1.10.1"
    const val desugaring = "2.0.4"
    const val extendedMaterialIcons = "1.6.4"
    const val composeCompiler = "2.1.10"
    const val detekt = "1.23.7"
    const val dokka = "1.9.20"
    const val kotlinJvmTarget = "17"
    const val dependencyUpdates = "0.52.0"
}
