object Versions {
    const val appcompat = "1.7.1"
    const val composeBom = "2025.09.00"
    const val material = "1.13.0"
    const val navigation = "2.9.4"
    const val coreKtx = "1.17.0"
    const val lifecycleRuntimeKtx = "2.8.7"
    const val activityCompose = "1.11.0"
    const val mockk = "1.14.5"
    const val junit = "4.13.2"
    const val extJunit = "1.3.0"
    const val espresso = "3.7.0"
    const val truthAssert = "1.4.5"
    const val coroutinesTest = "1.10.2"
    const val desugaring = "2.1.5"
    const val extendedMaterialIcons = "1.6.4"
    const val composeCompiler = "2.2.20"
    const val detekt = "1.23.8"
    const val dokka = "1.9.20"
    const val kotlinJvmTarget = "17"
    const val dependencyUpdates = "0.52.0"
}
