object Versions {
    const val appcompat = "1.6.1"
    const val composeBom = "2023.10.00"
    const val material = "1.9.0"
    const val navigation = "2.7.3"
    const val coreKtx = "1.12.0"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.7.2"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val espresso = "3.5.1"
    const val truthAssert = "1.1.5"
    const val coroutinesTest = "1.7.3"
    const val desugaring = "2.0.3"
    const val extendedMaterialIcons = "1.5.3"
    const val composeCompiler = "1.5.0"
    const val detekt = "1.23.0"
    const val kotlinJvmTarget = "1.8"
}
